# Generated by Django 3.0.3 on 2020-03-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_fresh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(verbose_name=True),
        ),
    ]
