# Generated by Django 3.0.3 on 2020-03-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_fresh', '0002_auto_20200302_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_phone',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
