# Generated by Django 3.0.3 on 2020-03-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_fresh', '0003_auto_20200302_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_salary',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
