# Generated by Django 3.0.3 on 2020-03-03 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fast_fresh', '0003_auto_20200302_1431'),
        ('fast_fresh', '0003_auto_20200303_0342'),
    ]

    operations = [
    ]
