# Generated by Django 3.0.3 on 2020-03-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_fresh', '0004_merge_20200303_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickup',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='client',
            name='client_phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
