# Generated by Django 3.0.3 on 2020-03-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_fresh', '0004_job_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='bill_time',
            field=models.TimeField(default='9:08:10'),
            preserve_default=False,
        ),
    ]
