# Generated by Django 3.0.3 on 2020-03-04 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fast_fresh', '0005_delivery_bill_time'),
        ('fast_fresh', '0005_auto_20200303_1850'),
    ]

    operations = [
    ]
