# Generated by Django 3.0.3 on 2020-03-05 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fast_fresh', '0005_delivery_bill_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fast_fresh.Store'),
            preserve_default=False,
        ),
    ]
