# Generated by Django 3.0.3 on 2020-03-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_fresh', '0006_pickup_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='pickup_status',
            field=models.CharField(max_length=15),
        ),
    ]
