# Generated by Django 3.0.3 on 2020-03-06 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fast_fresh', '0007_auto_20200306_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='bill_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fast_fresh.Bill'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('Entregado', 'Entregado'), ('No Entregado', 'No Entregado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='pickup_status',
            field=models.CharField(choices=[('Entregado', 'Entregado'), ('No Entregado', 'No Entregado')], max_length=15),
        ),
    ]
