# Generated by Django 3.0.3 on 2020-03-06 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fast_fresh', '0008_auto_20200306_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='bill_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fast_fresh.Bill'),
            preserve_default=False,
        ),
    ]
