# Generated by Django 3.0.3 on 2020-03-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_fresh', '0008_paymentmethod_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeestore',
            name='hired_date',
            field=models.DateField(),
        ),
    ]
