# Generated by Django 3.0.3 on 2020-03-05 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fast_fresh', '0009_auto_20200305_0359'),
        ('fast_fresh', '0006_pickup_store'),
    ]

    operations = [
    ]
