# Generated by Django 3.0.3 on 2020-03-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_fresh', '0009_auto_20200306_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_earned_points',
            field=models.IntegerField(null=True),
        ),
    ]
