# Generated by Django 3.0.3 on 2020-03-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_fresh', '0010_merge_20200305_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
