# Generated by Django 3.0.3 on 2020-03-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_fresh', '0012_exchangerate_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method_instrument',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
